# Generated by Django 5.0.6 on 2026-03-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
