# Generated by Django 5.0.6 on 2026-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_checkout_options_checkout_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
