# Generated by Django 5.2.12 on 2026-04-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_checkout_phone_alter_register_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('romance', 'Romance'), ('fantasy', 'Fantasy'), ('science_fiction', 'Science Fiction'), ('mystery', 'Mystery'), ('thrillers', 'Thrillers')], default='romance', max_length=20),
        ),
    ]
