# Generated by Django 5.2.12 on 2026-04-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_checkout_options_product_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('romance', 'Romance'), ('fantasy', 'Fantasy'), ('science_fiction', 'Science Fiction'), ('mystery', 'Mystery'), ('thrillers', 'Thrillers'), ('self_health_and_personal_growth', 'Self Health and Personal Growth'), ('health_fitness_and_wellness', 'Health Fitness and Wellness'), ('spirituality_and_philosophy', 'Spirituality and Philosophy'), ('science_natural_and_technology', 'Science Natural and Technology'), ('leadership_and_management', 'Leadership and Management'), ('productivity_and_time_management', 'Productivity and Time Management'), ('career_professional_development', 'Career Professional Development'), ('old_age_people', 'Old Age People'), ('holy_books_religious_texts_or_scriptures', 'Holy Books, Religious Texts, or Scriptures')], default='romance', max_length=100),
        ),
    ]
