# Generated by Django 5.2.12 on 2026-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_checkout_status_register_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
