# Generated by Django 5.2.12 on 2026-04-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_checkout_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_amount', models.IntegerField(default=0, help_text='Flat discount amount in ₹')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
