# Generated by Django 5.2.12 on 2026-06-09 06:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_load_initial_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommendation_tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for recommendations (e.g., education, motivation, adventure)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_pdf',
            field=models.FileField(blank=True, help_text='PDF summary of the book', null=True, upload_to='book_summaries/'),
        ),
        migrations.CreateModel(
            name='BookPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_purchases', to='myapp.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_purchases', to='myapp.register')),
            ],
            options={
                'ordering': ['-purchased_date'],
                'unique_together': {('user', 'product', 'purchased_date')},
            },
        ),
        migrations.CreateModel(
            name='PersonalizedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_reason', models.CharField(help_text='Why this book is recommended', max_length=500)),
                ('match_score', models.FloatField(default=0.0, help_text='Recommendation match score 0-100')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_viewed', models.BooleanField(default=False)),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='myapp.register')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'unique_together': {('user', 'recommended_product')},
            },
        ),
    ]
