from django.urls import path
from myapp import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('base/', views.base, name='base'),
    path('cart/', views.cart, name='cart'),
    path('search/', views.search, name='search'),
    path('faq/', views.faq, name='faq'),
    path('logout/', views.logout, name='logout'),
    path('shop/', views.shop, name='shop'),
    path('product/<int:id>/', views.product, name='product'),
    path('blog/', views.blog, name='blog'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('checkout/', views.checkout, name='checkout'),
    path('add_to_cart/<int:id>/', views.cart_add, name='add_to_cart'),
    path('cart_plus/<int:id>', views.cart_plus, name='cart_plus'),
    path('cart_minus/<int:id>', views.cart_minus, name='cart_minus'),
    path('cart_delete/<int:id>', views.cart_delete, name='cart_delete'),
    path('add_wishlist/<int:id>', views.add_wishlist, name='add_wishlist'),
    path('wishlist_delete/<int:id>', views.wishlist_delete, name='wishlist_delete'),
    path('submit_review/<int:id>/', views.submit_review, name='submit_review'),
    path('apply_coupon/', views.apply_coupon, name='apply_coupon'),
    path('remove_coupon/', views.remove_coupon, name='remove_coupon'),
    path('success/', views.payment_success, name='success'),
    path('profile/', views.profile, name='profile'),
    path('track_order/<int:id>/', views.track_order, name='track_order'),
    path('chat/', views.chat_ui, name='chat_ui'),
    path('chatbot/', views.chatbot_api, name='chatbot_api'),
    path('reports/monthly-pdf/', views.monthly_summary_pdf, name='monthly_summary_pdf'),
    path('reports/monthly-excel/', views.monthly_summary_excel, name='monthly_summary_excel'),
]
