# Generated by Django 5.2.12 on 2026-05-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
